# Generated by Django 3.2.9 on 2021-12-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True, verbose_name='计量单位')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='名称')),
                ('code', models.CharField(blank=True, default='', max_length=32, verbose_name='代号')),
                ('standards', models.CharField(blank=True, default='', max_length=64, verbose_name='规格')),
                ('exe_standard', models.CharField(blank=True, default='', max_length=64, verbose_name='执行标准')),
                ('guid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='指导价')),
                ('is_product', models.BooleanField(default=False, verbose_name='是否成品')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('raw_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_info.material', verbose_name='原材料ID')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material_info.unit')),
            ],
        ),
    ]
