# Generated by Django 3.2.9 on 2021-12-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='raw_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_info.material', verbose_name='原材料ID'),
        ),
    ]
