# Generated by Django 3.2.9 on 2021-12-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_info', '0002_alter_material_raw_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='raw_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_info.material', verbose_name='原材料ID'),
        ),
    ]
